### PR TITLE
WIP(sqla 1.4 compatibility)

### PR DESCRIPTION
**Pull request by stvnksslr**
This is a very basic attempt at getting sqlacodegen working with the latest release of sqla and is for the moment WIP

issues that will hopefully be solved by this
#132 
#131 

reference to similar issues faced by alembic when it needed to match 1.4 compatibility
https://github.com/sqlalchemy/alembic/issues/775

### CODE REVIEW

**Comment by stvnksslr** [comment]
Not yet but thats the plan, i think im close to getting it sorted.

**Comment by bfmcneill** [comment]
> bfmcneill Not yet but thats the plan, i think im close to getting it sorted.

I found a project that is a fork of sqlacodegen that for some reason has it solved already.  They also reverse engineer the index names too.  Not sure if that helps you but here is a link

https://github.com/shree14/sqlalchemy-modelgen

**Comment by stvnksslr** [comment]
woah i had not heard of this project, its got quite a few nice features in it aside from the sqla 1.4 fixes

**Comment by therealjojo** [comment]
> 
> 
> > bfmcneill Not yet but thats the plan, i think im close to getting it sorted.
> 
> I found a project that is a fork of sqlacodegen that for some reason has it solved already. They also reverse engineer the index names too. Not sure if that helps you but here is a link
> 
> https://github.com/shree14/sqlalchemy-modelgen

Looks like that library is locked to v1.3.19 of SQLAlchemy. It ran successfully with MSSQL but translated the Identity columns I had present to Integer(x,0),primary_key=True) columns where x was variable and subject to the current maximum of the column.

**Pull request closed without merging**
