### PR TITLE
Pin SQLAlchemy < 2.0.0

### PR DESCRIPTION
**Pull request by amacfie**

### CODE REVIEW

**Comment by amacfie** [comment]
Well there's https://github.com/agronholm/sqlacodegen/issues/236

**Comment by agronholm** [comment]
This project doesn't use `sqlalchemy.__all__`.

**Comment by amacfie** [comment]
https://github.com/agronholm/sqlacodegen/blob/f05d99e2a2a6d04b065ebad4b1d68a69b1e69572/src/sqlacodegen/generators.py#L244 ?

**Comment by agronholm** [comment]
Ah...I was looking at the most recent changes where this was eliminated. But indeed on GitHub master, it is still used.

**Comment by rbuffat** [comment]
> Ah...I was looking at the most recent changes where this was eliminated. But indeed on GitHub master, it is still used.

@agronholm Are these changes somewhere available? I would be interested in implementing a generator for SQLAlchemy2 (Although I'm not yet sure how difficult it will be and probably would require some guidance)

**Comment by agronholm** [comment]
I think I still need to make a post-release for the 2.x series since a lot of people are opening issues about problems with sqla 2.0.

**Pull request closed without merging**
