### PR TITLE
Fix translation of ARRAY-item types

### LINKED ISSUE #46: Type translations in array
Type translation does not seem to work in array data types, e.g.: 
`create table dpa_test(dpa double precision[]);`
produces
`t_dpa_test = Table(
    'dpa_test', metadata,
    Column('dpa', ARRAY(DOUBLE_PRECISION(precision=53)))
)
`
Yet, DOUBLE_PRECISION is not imported.

### PR DESCRIPTION
**Pull request by MGlauer**
* ARRAY-types are now translated recursively

closes #46

### CODE REVIEW

**Comment by aisayko** [comment]
+1 for this

**Comment by agronholm** [comment]
I'll consider merging this if you add the appropriate tests.

**Comment by agronholm** [comment]
If you could rebase this against latest master and add the tests from your other PR, I'll merge this.

**Comment by agronholm** [comment]
Your PR does not fix the problem of ARRAY item types not being imported.

**Comment by agronholm** [comment]
I made my own fix but I credited you in the changelog nonetheless for the inspiration :)

**Pull request closed without merging**
