### PR TITLE
Added --notables hack

### PR DESCRIPTION
**Pull request by Morabaraba**
Added --notables to sqlacodegen.

Not the cleanest method, but it works for me.

Just wanted to share. If cleanup is need to get request into master let me know what.

### CODE REVIEW

**Comment by agronholm** [comment]
Sorry, what is the point of this?

**Comment by Morabaraba** [comment]
Wanted to generate code without the table declarations; just the orm classes in the generated py code.

Added a `--notables` to accomplish it. Feels a bit "hacky". But it does the job.

**Comment by agronholm** [comment]
What about tables that do not have primary keys? And what about association tables? Are you just going to leave them out?

**Comment by Morabaraba** [comment]
Those can be issue(s) one run into by using this `--notables` hack.

But I have not found a issue yet for my (simple) use case. I dynamically load the ORM classes dynamically to create [`ModelView`](https://flask-admin.readthedocs.io/en/latest/api/mod_contrib_sqla/) classes to browse my db tables in a crud way.

I found the table declaration creating conflict with my sqlalchmy metdata engine and wanted a way to remove it.

**Comment by agronholm** [comment]
> I found the table declaration creating conflict with my sqlalchmy metdata engine and wanted a way to remove it.

That simple way would be to edit the generated models file and remove the tables you don't want.

Sorry, I cannot accept this PR.

**Pull request closed without merging**
